default_environment: dev
project_id: 019e6469-e2af-792e-9480-2203c83f47d6
environments:
- name: dev
- name: staging
- name: prod
python: python3.11
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-1-ap-northeast-2.pooler.supabase.com
      port: 5432
      user: postgres.hdsstnshkjzcccdaxlsb
    select:
    - public-resale_flat_prices_from_jan_2017.*
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git setuptools<80
    config:
      batch_size: 104857600
      credentials_path: /Users/tess/NTU/M2/dsai-m2-project-e4ba00fac89b.json
      dataset: resale
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: dsai-m2-project
